# Generated by Django 6.0.6 on 2026-07-02 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('target_score', models.IntegerField(default=85)),
                ('limit_drawdown', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('reward_badge', models.CharField(max_length=50)),
                ('badge_color', models.CharField(max_length=100)),
                ('participants', models.IntegerField(default=0)),
                ('success_rate', models.CharField(default='15%', max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.CharField(max_length=100)),
                ('logo', models.CharField(default='💼', max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('min_score', models.IntegerField(default=80)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('min_track_record', models.CharField(default='12 Months', max_length=50)),
                ('risk_profile', models.CharField(default='Low', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=50)),
                ('login_id', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('biography', models.TextField(blank=True, default='Swing trader focused on G10 currency models and strict drawdown parameters.')),
                ('style', models.CharField(default='Swing Trader', max_length=50)),
                ('experience', models.CharField(default='5 Years', max_length=50)),
                ('market', models.CharField(default='Forex, Metals', max_length=100)),
                ('goals', models.CharField(default='Establish $500k funded allocation with low daily risk parameters.', max_length=200)),
                ('available_for_funding', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('alpha_score', models.IntegerField(default=75)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('trade_type', models.CharField(max_length=10)),
                ('lots', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('stop_loss_used', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='api.connectedaccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_days', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollments', to='api.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
